# Generated by Django 4.2.5 on 2023-09-28 18:59

import catalog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя автора книги', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию автора книги', max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(help_text='Введите дата рождения автора книги', verbose_name='Дата рождения')),
                ('biography', models.TextField(help_text='Введите краткую биографию автора книги', max_length=2000, verbose_name='Краткая биография')),
                ('photo', models.ImageField(blank=True, help_text='Введите фото автора', null=True, upload_to='images', verbose_name='Фoтo автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название книги', max_length=100, verbose_name='Название книги')),
                ('description', models.TextField(help_text='Введите краткое описание книги', max_length=2000, verbose_name='Краткое описание книги')),
                ('isbn', models.CharField(help_text='Введите ISBN номер книги', max_length=20, verbose_name='ISBN номер книги.')),
                ('publication_date', models.IntegerField(help_text='Введите год издания книги', verbose_name='Год издания книги.')),
                ('authors', models.ManyToManyField(help_text='Введите автора книги', related_name='books', to='catalog.author', verbose_name='Автор книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Введите жанр книги', max_length=200, verbose_name='Жанр книги')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=catalog.models.get_upload_path_by_products, verbose_name='Изображение книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Изображение книги',
                'verbose_name_plural': 'Изображения книги',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Выберите жанр книги', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.genre', verbose_name='Жанр книги'),
        ),
    ]
